site_name: IDM Standards
site_url: https://InstituteforDiseaseModeling.github.io/idm_standards/
repo_name: InstituteforDiseaseModeling/idm_standards
repo_url: https://github.com/InstituteforDiseaseModeling/idm_standards
docs_dir: docs
theme:
  name: material
  custom_dir: docs_guidance/customization/overrides
  font:
    text: Roboto
    code: Roboto Mono
  logo: docs_guidance/images/idm-logo-transparent.png
  favicon: docs_guidance/images/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

nav:
  - Home: index.md
  - Getting started:
    - getting_started/README.md
    - Installing Python: getting_started/1_python.md
    - AI-assisted development: getting_started/2_ai.md
    - Coding guidelines: getting_started/3_guidelines.md
    - Communication and culture: getting_started/4_comms.md
  - Engineering guidance:
    - eng_guidance/README.md
    - Philosophy: eng_guidance/1_philosophy.md
    - Python: eng_guidance/2_python.md
    - Tests: eng_guidance/3_tests.md
    - Documentation: eng_guidance/4_documentation.md
    - Other: eng_guidance/5_other.md
    - Zen: eng_guidance/6_zen.md
    - Quality guidelines: eng_guidance/engineering_quality_guidelines.md
  - Engineering processes:
    - eng_process/README.md
    - GitHub: eng_process/github.md
    - Processes: eng_process/processes.md
    - Public release: eng_process/public_release.md
  - Docs guidance:
    - docs_guidance/index.md
    - MkDocs overview: docs_guidance/mkdocs.md
    - Quarto overview: docs_guidance/quarto.md
    - Home page: docs_guidance/home.md
    - Installation page: docs_guidance/install.md
    - TOC organization and topic types:
      - docs_guidance/topic-types/index.md
      - Tutorial: docs_guidance/topic-types/tutorial.md
      - Example notebook: docs_guidance/topic-types/notebook.ipynb
      - How-to: docs_guidance/topic-types/howto.md
      - Reference: docs_guidance/topic-types/reference.md
      - Explanation: docs_guidance/topic-types/explanation.md
    - Personas:
      - docs_guidance/personas/index.md
      - Model builder: docs_guidance/personas/model-builder.md
      - Model extender: docs_guidance/personas/model-extender.md
      - Model user: docs_guidance/personas/model-user.md
      - Policy influencer: docs_guidance/personas/policy-influencer.md
      - Policy maker: docs_guidance/personas/policy-maker.md
    - Style and grammar: docs_guidance/vale.md

# icons, semantic markup, emojis
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTML and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - pymdownx.emoji: # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # Latex processing for math equations
      generic: true
  - pymdownx.snippets: # insert content from other files
      auto_append:
        - docs_guidance/includes/glossary.md # definitions for glossary entries
  - abbr # term/abbreviation hover descriptions
  - pymdownx.blocks.details: # allows nesting of collapsible code
  - pymdownx.highlight: # syntax highlighting for code blocks
      linenums: true
      default_lang: 'python'
  - pymdownx.inlinehilite # syntax highlighting for inline code
  - pymdownx.superfences # enables code, diagram fences to be nested in lists, etc.
  - pymdownx.details # collapsible elements
  - pymdownx.tabbed: # tabbed content that can be toggled
      alternate_style: true
  - pymdownx.blocks.caption # captions for images, tables, etc.

# javascript and CSS customization
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - docs_guidance/customization/css/extra.css # custom CSS for footer spacing

validation:
  not_in_nav: info # glossary.md is auto-appended, not navigated
  absolute_links: info

plugins:
  - search # search functionality
  - autorefs # automatically create linkable references
  - include-markdown # include other files, such as READMEs
  - table-reader # enables rendering of CSV/TSV files as tables
  - mkdocs-jupyter: # enables Jupyter notebooks to be rendered
      execute: true
      allow_errors: false # set to true to continue executing cells even if one fails
      include_source: true

copyright: Copyright &copy; 2026 Gates Foundation. All rights reserved.

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InstituteforDiseaseModeling/idm_standards
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling

  analytics:
    provider: custom
    tracking_id: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
