StylesPath = .github/styles
Vocab = IDM
MinAlertLevel = suggestion

# Packages = Microsoft, write-good
# ^ commenting out so only local changes are applied. 


# You can change (or add) file extensions here
# to apply these settings to other file types.

# regular linting for mkdocs and quarto source files
[*.{md,qmd}]
BasedOnStyles = IDM, Vale, Microsoft, write-good
Vale.Terms = NO
# ^ too many false positives with this rule

# Only lint links in notebook files. 
# Links are not well-handled and need counterintuitive 
# formatting to be parsed correctly.
[*.ipynb] # exclude notebooks from other style linters, many false positives
BasedOnStyles = Notebooks

# exclude claude skills completely
[.claude/**/*]
BasedOnStyles =