name: Quarto Build on PR

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Build Quarto site
      run: quarto render
