name: Quarto Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - working-directory: docs
        run: pip install -r requirements.txt

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          path: docs
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
